# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 173730eedb57dd7e8224338f93fcd239f3d725d0c989903ce8de1d58b107c577244d215b3aff110ce1c467662ec2b029fdcda9bd9f33d299496bf6519eb5be48

test:
  secret_key_base: b6e97622dbe9c39a37c1f062dbe8d92c62c28f9e643a6245f6d890ca436713d806a5b8e0b95cba36cadb24d604f5a094c42aab01c82755fd35a1cb5234868019

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
